CREATE TABLE ACCOUNTS (
  ID             INTEGER IDENTITY(1, 1) NOT NULL PRIMARY KEY,
  ACCOUNT_NUMBER INTEGER(10) NOT NULL,
  CURRENCY       VARCHAR(3) NOT NULL,
  AMOUNT         INTEGER(20) NOT NULL
);

CREATE TABLE CUSTOMERS (
  ID         INTEGER IDENTITY(1, 1) NOT NULL PRIMARY KEY,
  NAME       VARCHAR(30) NOT NULL,
  ACCOUNT_ID INTEGER(10) NOT NULL,
  CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID)
    REFERENCES ACCOUNTS(ID)
);

CREATE TABLE CURRENCY_RATES (
  ID         INTEGER IDENTITY(1, 1) NOT NULL PRIMARY KEY,
  CURRENCY1  VARCHAR(3) NOT NULL,
  CURRENCY2  VARCHAR(3) NOT NULL,
  MULTIPLIER FLOAT NOT NULL
);